# Generated by Django 4.2.11 on 2024-04-28 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiofile',
            name='emotion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
